Repository TrishanCodeCrafter/611_project-application-template, pull requests merged in 2024-11, with the labels that each got.

#3 Adds: issue dependeny analyser with custom tree
  CommonIssueAnalyser.py
  TriageAnalysis.py
  requirements.txt
  run.py
  tree_visualizer.py
Labels: enhancement

#4 Feature addition
  frequency_of_issue_creation.py
  run.py
Labels: enhancement

#5 adds: README with feature discription
  README.md
Labels: documentation

#6 fixes: README with feature discription
  README.md
Labels: bug, documentation
